#!/bin/bash
# LAST BERTH — регресс одной командой.
#   bash tools/regress.sh smoke            один сквозной сценарий (~1 мин)
#   bash tools/regress.sh full             все живые сценарии + боты; дробится по бюджету вызова, см. --resume
#   bash tools/regress.sh pw24 pw26 sim    только указанные
# Флаги: --shots (скриншоты ложатся в work/.run/*.png), --resume (продолжить прерванный full), --fresh (work из live/index.html
#        заново — правки core/ui в work будут потеряны), --rebaseline (записать текущие цифры ботов как эталон)
# Вывод: одна строка на сценарий; при падении — до 10 упавших проверок. Полные логи: work/logs/<имя>.log
# Бутстрап идемпотентен: work/ (live.html, core.js, ui.js, page.html). Playwright и Chromium — из node_modules репозитория
# (один раз: npm i && npx playwright install chromium). Работает в Linux и в Git Bash на Windows.
# Переменные: LB_WORK (рабочая папка), LB_CHROMIUM (свой браузер), PYTHON (интерпретатор), BUDGET (секунд на вызов, 0 = без лимита).
set -u
T="$(cd "$(dirname "$0")" && pwd)"; LB="$(dirname "$T")"; W="${LB_WORK:-$LB/work}"
R="$W/.run"; LOG="$W/logs"; ST="$LOG/full.state"; BUDGET=${BUDGET:-0}; T0=$(date +%s)
# python: PYTHON, иначе python3, иначе py -3 (на Windows python3 — заглушка магазина); вывод и файлы — utf-8
if [ -n "${PYTHON:-}" ]; then PY="$PYTHON"; elif python3 -c 1 2>/dev/null; then PY=python3; else PY="py -3"; fi
export PYTHONUTF8=1 PYTHONIOENCODING=utf-8
command -v node >/dev/null || PATH="/c/Program Files/nodejs:$PATH"
np() { if command -v cygpath >/dev/null; then cygpath -m "$1"; else echo "$1"; fi; }   # путь в виде, который понимает node
# Живые сценарии (full). Правка списка — после решения по аудиту (last-berth/AUDIT.md).
FULL="pw9 pw13 pw15 pw16 pw17 pw18 pw19 pw20 pw21 pw22 pw23 pw24 pw25 pw26 pw27 pw28 pw29 pw30 pw31 pw32 pw33 pw34 pw35 pw36 sim"
SIM_ARGS="3000 11,22,33,44,55,66,77,88"
SHOTS=0 RESUME=0 FRESH=0 REBASE=0 NAMES=()
for a in "$@"; do case "$a" in
  --shots) SHOTS=1;; --resume) RESUME=1;; --fresh) FRESH=1;; --rebaseline) REBASE=1;;
  smoke) NAMES+=(smoke);; full) MODE=full; NAMES+=($FULL);; -h|--help) sed -n 2,11p "$0"; exit 0;;
  *) NAMES+=("$a");; esac; done
[ ${#NAMES[@]} -eq 0 ] && { sed -n 2,11p "$0"; exit 2; }
MODE=${MODE:-list}
mkdir -p "$W" "$LOG" "$R"

# ---------- бутстрап ----------
$PY - "$LB/live/index.html" "$W" "$FRESH" <<'PY' || exit 1
import sys,os,re,shutil
src,W,fresh=sys.argv[1],sys.argv[2],sys.argv[3]=='1'
L=os.path.join(W,'live.html'); cut=lambda s:re.findall(r'<script>\n(.*?)</script>',s,re.S)
rd=lambda p:open(p,encoding='utf-8').read()
def reset():
    shutil.copyfile(src,L); b=cut(rd(L)); assert len(b)==2,'live.html: ждал два <script> (core, ui)'
    for n,x in zip(('core.js','ui.js'),b): open(os.path.join(W,n),'w',encoding='utf-8').write(x)
have=all(os.path.exists(os.path.join(W,n)) for n in ('live.html','core.js','ui.js'))
if fresh or not have: reset(); sys.exit()
if rd(src)!=rd(L):
    b=cut(rd(L)); clean=b==[rd(os.path.join(W,'core.js')),rd(os.path.join(W,'ui.js'))]
    if clean: reset(); print('work: live.html обновлён из live/index.html')
    else: print('WARN: live/index.html отличается от work/live.html, а в work есть правки core/ui — сверь; --fresh сбросит правки')
PY
for f in new-texts.tsv changed-texts.tsv; do [ -f "$W/$f" ] || : > "$W/$f"; done
( cd "$W" && node --check core.js && node --check ui.js && $PY "$T/build.py" ) > "$LOG/build.log" 2>&1 \
  || { echo "BUILD FAIL — $(tail -3 "$LOG/build.log" | tr '\n' ' ')"; exit 1; }
grep -q "added 0 · already baked 0 · changed 0" "$LOG/build.log" || echo "build: $(tail -1 "$LOG/build.log")"
# MAP.md — оглавление кода; пересобирается, только если core.js/ui.js новее
[ "$W" = "$LB/work" ] && { [ "$W/core.js" -nt "$LB/MAP.md" ] || [ "$W/ui.js" -nt "$LB/MAP.md" ]; } && $PY "$T/map.py" "$W" | tr -d '\r' > "$LB/MAP.md"

need_browser=0; for n in "${NAMES[@]}"; do [ "$n" != sim ] && need_browser=1; done
if [ $need_browser = 1 ]; then
  ( cd "$LB" && node -e "require('playwright')" ) 2>/dev/null || { echo "RUNTIME FAIL — нет playwright: в корне репозитория npm i && npx playwright install chromium"; exit 1; }
  cat > "$R/pw-shim.js" <<JS
// generated by regress.sh: playwright from the repository's node_modules; screenshots are no-ops unless --shots
const pw=require('$(np "$LB")/node_modules/playwright'); const L=pw.chromium.launch.bind(pw.chromium);
const wrap=p=>{ if(!process.env.LB_SHOTS){ p.screenshot=async()=>Buffer.alloc(0) } return p };
pw.chromium.launch=async(o={})=>{ const b=await L(o);
  const np=b.newPage.bind(b); b.newPage=async(...a)=>wrap(await np(...a));
  const nc=b.newContext.bind(b); b.newContext=async(...a)=>{ const c=await nc(...a); const cp=c.newPage.bind(c); c.newPage=async(...x)=>wrap(await cp(...x)); return c };
  return b };
module.exports=pw;
JS
  # сценарии ждут плоскую папку (pw11.js, fonts-local.css рядом) — копии в work/.run; пути берутся из LB_WORK / LB_PLAYWRIGHT
  for f in "$T"/pw*.js "$T"/smoke.js; do [ -f "$f" ] || continue; cmp -s "$f" "$R/$(basename "$f")" || cp "$f" "$R/"; done
  cmp -s "$T/fonts-local.css" "$R/fonts-local.css" || cp "$T/fonts-local.css" "$R/"
fi

# ---------- прогон ----------
# free-form сценарии (без PASS/FAIL) проверяются по tools/regress-expect.tsv: имя \t описание \t регэксп по логу
judge() {  # $1 name, $2 log, $3 exit code → печатает строку итога и до 10 упавших
  local n=$1 f=$2 rc=$3
  if grep -qE '^(PASS|FAIL) ' "$f"; then
    local p=$(grep -c '^PASS ' "$f") t=$(grep -cE '^(PASS|FAIL|ERROR) ' "$f")
    local was=$(grep "^$n " "$LOG/counts" 2>/dev/null | tail -1 | cut -d' ' -f2); was=${was:-0}
    if [ "$p" = "$t" ] && [ "$rc" = 0 ] && [ "$t" -ge "$was" ]; then echo "$n $p/$t PASS"; echo "$n $t" >> "$LOG/counts"
    else echo "$n $p/$t FAIL"; grep -E '^(FAIL|ERROR) ' "$f" | head -10 | cut -c1-200 | sed 's/^/  /'
      [ "$t" -lt "$was" ] && echo "  проверок $t, в прошлом зелёном прогоне было $was — сценарий оборвался раньше"
      [ "$rc" != 0 ] && echo "  exit $rc: $(grep -m2 -E '(Error|Timeout|exceeded|ERR_|waiting for)' "$f" | tr '\n' ' ' | cut -c1-200)"; fi
  else
    $PY - "$n" "$f" "$rc" "$T/regress-expect.tsv" <<'PY'
import sys,re
def crash(log):
    L=[x.strip() for x in log.splitlines() if re.search(r'(Error|Timeout|exceeded|ERR_|waiting for)',x)]
    return ' | '.join(L[:2])[:200] or ' | '.join(log.strip().splitlines()[-2:])[:200]
n,f,rc,ex=sys.argv[1:]; log=open(f,encoding='utf-8',errors='replace').read()
rules=[l.rstrip('\n').split('\t') for l in open(ex,encoding='utf-8') if l.startswith(n+'\t')]
fails=[]
if rc!='0': fails.append('exit %s: %s'%(rc,crash(log)))
for r in rules:
    d,rx=r[1],r[2]; k=int(r[3]) if len(r)>3 and r[3] else 1
    if rx.startswith('!'):
        if re.search(rx[1:],log,re.M): fails.append(d)
    elif len(re.findall(rx,log,re.M))<k: fails.append(d)
if not rules: fails.append('нет правил в tools/regress-expect.tsv')
t=len(rules)+1; p=max(0,t-len(fails))
print('%s %d/%d %s'%(n,p,t,'PASS' if not fails else 'FAIL'))
for x in fails[:10]: print('  '+x[:200])
PY
  fi
}
run_sim() {
  ( cd "$W" && timeout 170 node "$T/sim.js" core.js $SIM_ARGS ) > "$LOG/sim.log" 2>&1; local rc=$?
  $PY - "$LOG/sim.log" "$rc" "$T/sim-baseline.tsv" "$REBASE" <<'PY'
import sys,os
f,rc,base,reb=sys.argv[1:]; L=open(f).read().splitlines()
if rc!='0' or len(L)<6: print('sim FAIL exit',rc,'—',' | '.join(L[-2:])[:200]); sys.exit()
hd=L[1].split('\t'); body=[r for r in L[2:] if r.strip()]; rows={r.split('\t')[0]:dict(zip(hd,r.split('\t'))) for r in body}
def let(b):
    a,n=map(int,rows[b]['alive'].split('/')); return 'L' if a==0 else ('W' if 2*a>=n else '?')
Lt={b:let(b) for b in rows}; sc={b:float(rows[b]['score']) for b in rows}
inv=Lt['idle']=='L' and Lt['greedy']=='L' and Lt['pro']=='W' and sc['pro']==max(sc.values())
cur='\n'.join([L[1]]+body)+'\n'
if reb=='1' or not os.path.exists(base): open(base,'w',newline='\n').write(cur); note='эталон записан'
else:
    B=open(base).read(); note='= эталон' if B==cur else 'ОТЛИЧАЕТСЯ от эталона (diff: work/logs/sim.log vs tools/sim-baseline.tsv)'
st='FAIL' if 'ОТЛИЧ' in note else 'PASS'
alive=rows['pro']['alive']
print('sim %s  idle:%s greedy:%s expand:%s pro:%s(жив %s) · счёт %s · %s · инвариант %s'%(st,Lt['idle'],Lt['greedy'],Lt['expand'],Lt['pro'],alive,
      '/'.join(rows[b]['score'] for b in rows),note,'OK' if inv else 'НЕ выполнен (pro не W)'))
PY
}
run_one() {  # $1 name → строка итога в stdout
  local n=$1
  if [ "$n" = sim ]; then run_sim; return; fi
  [ -f "$R/$n.js" ] || { echo "$n ? нет tools/$n.js"; return; }
  local t1=$(date +%s)
  ( cd "$R" && LB_WORK="$(np "$W")" LB_PLAYWRIGHT="$(np "$R/pw-shim.js")" LB_SHOTS=$([ $SHOTS = 1 ] && echo 1) timeout 165 node "$n.js" ) > "$LOG/$n.log" 2>&1; local rc=$?
  echo "$n $(( $(date +%s)-t1 ))" >> "$LOG/durations"
  judge "$n" "$LOG/$n.log" "$rc"
}
est() { local d=$(grep "^$1 " "$LOG/durations" 2>/dev/null | tail -1 | cut -d' ' -f2); echo "${d:-40}"; }

if [ "$MODE" = full ]; then
  [ $RESUME = 1 ] || : > "$ST"
  for n in "${NAMES[@]}"; do
    grep -q "^$n " "$ST" 2>/dev/null && continue
    if [ "$BUDGET" -gt 0 ] && [ $(( $(date +%s)-T0+$(est "$n") )) -gt "$BUDGET" ]; then
      echo "full: готово $(grep -c '^[^ ]' "$ST")/${#NAMES[@]} — бюджет вызова исчерпан, продолжить: bash tools/regress.sh full --resume"; exit 3; fi
    run_one "$n" >> "$ST"
  done
  cat "$ST"; ! grep -q "FAIL" "$ST"
else
  bad=0; for n in "${NAMES[@]}"; do out=$(run_one "$n"); echo "$out"; echo "$out" | head -1 | grep -q FAIL && bad=1; done; exit $bad
fi
